// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package php

import (
	"bufio"
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/filesystem"
)

const (
	gapicMetadataFile = "gapic_metadata.json"
	phpExtension      = ".php"
	// Limit reading to 50 lines. In google-cloud-php, markers are found early:
	// line 2 for Protobuf files and line 19 for GAPIC files.
	maxLinesToCheck = 50
)

var (
	gapicMarker        = []byte("GENERATED CODE WARNING")
	protobufMarker     = []byte("Generated by the protocol buffer compiler")
	directoriesToClean = []string{
		"src",
		"tests",
		"metadata",
		"samples",
	}
)

// Clean removes all generated code from beneath the given library's
// output directory. If the output directory does not currently exist, this
// function is a no-op.
func Clean(library *config.Library) error {
	keepSet := make(map[string]bool)
	for _, k := range library.Keep {
		keepSet[k] = true
	}
	for _, dir := range directoriesToClean {
		if err := cleanFiles(library, keepSet, dir); err != nil {
			return err
		}
		targetDir := filepath.Join(library.Output, dir)
		keepFunc := func(rel string) bool {
			return keepSet[rel]
		}
		if err := filesystem.RemoveEmptyDirs(targetDir, library.Output, keepFunc); err != nil {
			return err
		}
	}
	return nil
}

// cleanFiles walks the given subdirectory under the library output and removes
// generated files. It preserves files listed in the keep set. A file is considered
// generated if it is named "gapic_metadata.json" or if it is a ".php" file containing
// either the GAPIC or Protobuf code generation warning markers.
func cleanFiles(lib *config.Library, keepSet map[string]bool, subDir string) error {
	dir := filepath.Join(lib.Output, subDir)
	_, err := os.Stat(dir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil
		}
		return err
	}
	return filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		relPath, err := filepath.Rel(lib.Output, path)
		if err != nil {
			return err
		}
		if keepSet[filepath.ToSlash(relPath)] {
			return nil
		}
		if d.Name() == gapicMetadataFile {
			return os.Remove(path)
		}
		if !strings.HasSuffix(d.Name(), phpExtension) {
			return nil
		}
		hasMarker, err := fileHasMarker(path)
		if err != nil {
			return err
		}
		if hasMarker {
			return os.Remove(path)
		}
		return nil
	})
}

// fileHasMarker checks if the file at path contains either gapicMarker or
// protobufMarker within its first maxLinesToCheck lines.
func fileHasMarker(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for i := 0; i < maxLinesToCheck && scanner.Scan(); i++ {
		line := scanner.Bytes()
		if bytes.Contains(line, gapicMarker) || bytes.Contains(line, protobufMarker) {
			return true, nil
		}
	}
	err = scanner.Err()
	// A line >64KB is likely not in a generated file. Skip instead of failing.
	if errors.Is(err, bufio.ErrTooLong) {
		return false, nil
	}
	return false, err
}
