# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file contains a wrapper build configuration for testing.
load(
    "@com_google_googleapis_imports//:imports.bzl",
    "ruby_cloud_gapic_library",
)

ruby_cloud_gapic_library(
    name = "automl_ruby_wrapper",
    srcs = ["//google/cloud/automl/v1:automl_proto_with_info"],
    extra_protoc_parameters = [
        "ruby-cloud-env-prefix=AUTOML",
        "ruby-cloud-namespace-override=AutoMl=AutoML;Automl=AutoML",
        "ruby-cloud-path-override=auto_ml=automl",
    ],
)
