# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This runs the `librarian release tag-and-release` command with a provided repository,
# secret name, and optional PR
steps:
  - name: golang:1.25.0
    id: publish-release-dispatcher
    entrypoint: go
    args:
      - 'run'
      - './cmd/automation'
      - '--project=$PROJECT_ID'
      - '--command=publish-release'
    secretEnv: ['LIBRARIAN_GITHUB_TOKEN']
tags: ['publish-release-dispatcher']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/$_GITHUB_TOKEN_SECRET_NAME/versions/latest
      env: 'LIBRARIAN_GITHUB_TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY
